/*
 * Copyright 2018 Aluno.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package view;

import model.Cliente;
import dao.ClienteDAO;
import swing.PromptComboBoxRenderer;
import swing.event.MyMouseAdapter;
import util.SwingUtils;
import util.TextUtils;
import values.SoftConfig;

import com.towel.bind.annotation.Bindable;
import com.towel.bind.annotation.Form;
import com.towel.swing.table.ObjectTableModel;

import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

import org.hibernate.HibernateException;
import util.Validator;

/**
 *
 * @author Aluno
 */
@Form(Cliente.class)
public class ClienteView extends BaseView {

    /**
     * Creates new form ClienteView
     * @param parent
     * @param modal
     */
    public ClienteView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    } // fim do método construtor ClienteView

    @Override
    protected void init() {
        initComponents();
        txtCPF.setFocusLostBehavior(JFormattedTextField.COMMIT);
        txtTelefone.setFocusLostBehavior(JFormattedTextField.COMMIT);
        txtCEP.setFocusLostBehavior(JFormattedTextField.COMMIT);
        cbEstado.setRenderer(new PromptComboBoxRenderer("--"));
    } // fim do método init

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultar = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbFiltro = new javax.swing.JComboBox<>();
        btConsultar1 = new javax.swing.JButton();
        txtConsulta = new javax.swing.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        btSelecionar = new javax.swing.JButton();
        btCancelarConsulta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JCFormattedTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JCTextField();
        SwingUtils.setFieldLength(txtNome, values.Length.Cliente.NOME, SwingUtils.FIXED_LENGTH);
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JCTextField();
        SwingUtils.setFieldLength(txtEmail, values.Length.Cliente.EMAIL, SwingUtils.FIXED_LENGTH);
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JCFormattedTextField();
        lblDtNascimento = new javax.swing.JLabel();
        dtNascimento = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JCTextField();
        SwingUtils.setFieldLength(txtEndereco, values.Length.Cliente.ENDERECO, SwingUtils.FIXED_LENGTH);
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JCTextField();
        SwingUtils.setFieldLength(txtNumero, values.Length.Cliente.NUM, SwingUtils.FIXED_LENGTH);
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JCTextField();
        SwingUtils.setFieldLength(txtBairro, values.Length.Cliente.BAIRRO, SwingUtils.FIXED_LENGTH);
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JCTextField();
        SwingUtils.setFieldLength(txtComplemento, values.Length.Cliente.COMPLEMENTO, SwingUtils.FIXED_LENGTH);
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JCTextField();
        SwingUtils.setFieldLength(txtCidade, values.Length.Cliente.CIDADE, SwingUtils.FIXED_LENGTH);
        lblEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        lblCEP = new javax.swing.JLabel();
        txtCEP = new javax.swing.JCFormattedTextField();
        btConsultar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btIncluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        consultar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("res/Bundle"); // NOI18N
        consultar.setTitle(bundle.getString("ClienteView.consultar.title")); // NOI18N
        consultar.setMinimumSize(new java.awt.Dimension(726, 400));
        consultar.setModal(true);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")), bundle.getString("ClienteView.jPanel7.border.title"))); // NOI18N

        jLabel17.setText(bundle.getString("filtro")); // NOI18N

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<String>(bundle.getString("ClienteView.cbFiltro.array").split(",")));
        cbFiltro.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        btConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_search_18pt.png"))); // NOI18N
        btConsultar1.setText(bundle.getString("consultar")); // NOI18N
        btConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultar1ActionPerformed(evt);
            }
        });

        txtConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        txtConsulta.setPlaceholder(bundle.getString("consulta.placeholder")); // NOI18N
        txtConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(btConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar1))
                .addGap(10, 10, 10))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaClienteMouseReleased(evt);
            }
        });
        tabelaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaClienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCliente);

        btSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_done_18pt.png"))); // NOI18N
        btSelecionar.setText(bundle.getString("selecionar")); // NOI18N
        btSelecionar.setEnabled(false);

        btCancelarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_cancel_18pt.png"))); // NOI18N
        btCancelarConsulta.setText(bundle.getString("cancelar")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btCancelarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelecionar)
                    .addComponent(btCancelarConsulta))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar.getContentPane());
        consultar.getContentPane().setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(bundle.getString("ClienteView.title")); // NOI18N
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")), bundle.getString("ClienteView.jPanel2.border.title"))); // NOI18N

        lblCPF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCPF.setText(bundle.getString("ClienteView.lblCPF.text")); // NOI18N

        txtCPF.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFFocusGained(evt);
            }
        });

        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText(bundle.getString("ClienteView.lblNome.text")); // NOI18N

        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText(bundle.getString("ClienteView.lblEmail.text")); // NOI18N

        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefone.setText(bundle.getString("ClienteView.lblTelefone.text")); // NOI18N

        txtTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDtNascimento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDtNascimento.setText(bundle.getString("ClienteView.lblDtNascimento.text")); // NOI18N

        dtNascimento.setDateFormatString(bundle.getString("dateFormatString")); // NOI18N
        dtNascimento.setMaxSelectableDate(new Date());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDtNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")), bundle.getString("ClienteView.jPanel3.border.title"))); // NOI18N

        lblEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEndereco.setText(bundle.getString("ClienteView.lblEndereco.text")); // NOI18N

        txtEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumero.setText(bundle.getString("ClienteView.lblNumero.text")); // NOI18N

        txtNumero.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        lblBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBairro.setText(bundle.getString("ClienteView.lblBairro.text")); // NOI18N

        txtBairro.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        lblComplemento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblComplemento.setText(bundle.getString("ClienteView.lblComplemento.text")); // NOI18N

        txtComplemento.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        lblCidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCidade.setText(bundle.getString("ClienteView.lblCidade.text")); // NOI18N

        txtCidade.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText(bundle.getString("ClienteView.lblEstado.text")); // NOI18N

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbEstado.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        lblCEP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCEP.setText(bundle.getString("ClienteView.lblCEP.text")); // NOI18N

        txtCEP.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(lblNumero)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplemento)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(lblEstado)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCEP)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        btConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_search_18pt.png"))); // NOI18N
        btConsultar.setText(bundle.getString("consultar")); // NOI18N
        btConsultar.setName("btConsultar"); // NOI18N

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_fiber_new_18pt.png"))); // NOI18N
        btNovo.setText(bundle.getString("novo")); // NOI18N

        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_add_18pt.png"))); // NOI18N
        btIncluir.setText(bundle.getString("incluir")); // NOI18N

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_update_18pt.png"))); // NOI18N
        btAlterar.setText(bundle.getString("alterar")); // NOI18N
        btAlterar.setEnabled(false);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_delete_forever_18pt.png"))); // NOI18N
        btExcluir.setText(bundle.getString("excluir")); // NOI18N
        btExcluir.setEnabled(false);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_cancel_18pt.png"))); // NOI18N
        btCancelar.setText(bundle.getString("cancelar")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCancelar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btNovo)
                        .addComponent(btConsultar)
                        .addComponent(btIncluir)
                        .addComponent(btAlterar)
                        .addComponent(btExcluir)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaClienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClienteMouseReleased
        if (tabelaCliente.getSelectedRow() != -1) {
            btSelecionar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaClienteMouseReleased

    private void txtConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            consultar();
        }
    }//GEN-LAST:event_txtConsultaKeyPressed

    private void tabelaClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaClienteKeyReleased
        if (tabelaCliente.getSelectedRow() != -1) {
            btSelecionar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaClienteKeyReleased

    private void btConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultar1ActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultar1ActionPerformed

    private void txtCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusGained
        txtCPF.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
    }//GEN-LAST:event_txtCPFFocusGained

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
    }//GEN-LAST:event_txtNomeFocusGained

    @Override
    protected void callConsulta() throws HeadlessException {
        consultar.setSize(SoftConfig.WINDOW_WIDTH, consultar.getHeight());
        consultar.setLocationRelativeTo(null);
        cbFiltro.setSelectedIndex(0);
        txtConsulta.setText(null);

        try {
            carregarTabela(Cliente.class, new ClienteDAO().listar(), bundle.getString("ClienteView.tabela.vazia"), 
                    jScrollPane1, tabelaCliente, bundle.getString("ClienteView.tabela.header"));
            btSelecionar.setEnabled(false);
            consultar.setVisible(true);
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(getParent(),
                    bundle.getString("ClienteView.erroCarregar"),
                    bundle.getString("ClienteView.erroCarregarTitle"),
                    JOptionPane.ERROR_MESSAGE);
        }
    } // Fim do método callConsulta

    @Override
    protected void consultar() {
        String busca = txtConsulta.getText().trim();

        if (busca != null && !busca.isEmpty()) {
            try {
                Map<Integer, Runnable> map = new HashMap<>();
                map.put(0, () -> {
                    carregarTabela(Cliente.class, new ClienteDAO().consultarPorLike("nome", busca), 
                            bundle.getString("ClienteView.tabela.vazia"), jScrollPane1, tabelaCliente, 
                            bundle.getString("ClienteView.tabela.header"));
                });
                map.put(1, () -> {
                    carregarTabela(Cliente.class, new ClienteDAO().consultarPorLike("nuCpf", busca), 
                            bundle.getString("ClienteView.tabela.vazia"), jScrollPane1, tabelaCliente, 
                            bundle.getString("ClienteView.tabela.header"));
                });
                map.get(cbFiltro.getSelectedIndex()).run();
            } catch (HibernateException e) {
                JOptionPane.showMessageDialog((Frame) getParent(),
                        bundle.getString("erroBusca"));
            }
        } else {
            carregarTabela(Cliente.class, new ClienteDAO().listar(), 
                    bundle.getString("ClienteView.tabela.vazia"), jScrollPane1, tabelaCliente, 
                    bundle.getString("ClienteView.tabela.header"));
        }
        
        btSelecionar.setEnabled(false);
    } // fim do método consultar

    @Override
    protected void novo() throws HeadlessException {
        if (!TextUtils.getValueWithoutMask(txtCPF.getText()).isEmpty()
                || !txtNome.getText().trim().isEmpty()
                || !txtEmail.getText().trim().isEmpty()
                || !TextUtils.getValueWithoutMask(txtTelefone.getText()).isEmpty()
                || dtNascimento.getDate() != null
                || !txtEndereco.getText().trim().isEmpty()
                || !txtNumero.getText().trim().isEmpty()
                || !txtBairro.getText().trim().isEmpty()
                || !txtComplemento.getText().trim().isEmpty()
                || !txtCidade.getText().trim().isEmpty()
                || cbEstado.getSelectedIndex() > 0
                || !TextUtils.getValueWithoutMask(txtCEP.getText()).isEmpty()) {
            if (JOptionPane.showConfirmDialog((Frame) getParent(),
                    bundle.getString("ClienteView.confirmarNovo"),
                    bundle.getString("novo"), 0) == 0) {
                reset(true);
            }
        } else {
            limpar();
            txtCPF.requestFocus();
        }
    } // Fim do método novo

    @Override
    protected void incluir() {
        if (isFormValid() && isCPFValid()) {
            entity = new Cliente();
            binder.updateModel(entity);

            if (new ClienteDAO().consultarPorEqUk("nuCpf", ((Cliente) entity).getNuCpf()) != null) {
                JOptionPane.showMessageDialog((Frame) getParent(),
                        bundle.getString("ClienteView.cpfExiste"),
                        bundle.getString("atencao"),
                        JOptionPane.WARNING_MESSAGE);
                txtCPF.requestFocus();

                return;
            }

            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(),
                        bundle.getString("ClienteView.confirmarIncluir"),
                        bundle.getString("incluir"), 0) == 0) {
                    new ClienteDAO().salvar((Cliente) entity); // incluir
                    JOptionPane.showMessageDialog((Frame) getParent(),
                            bundle.getString("ClienteView.incluidoSucesso"));
                    reset(true);
                }
            } catch (HibernateException | HeadlessException e) {
                JOptionPane.showMessageDialog((Frame) getParent(),
                        bundle.getString("ClienteView.erroIncluir")
                        + "\n<html><b>" + e.getClass() + "</html></b>\n"
                        + bundle.getString("contateDesenvolvedor"),
                        bundle.getString("ClienteView.erroIncluirTitle"),
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    } // fim do método incluir

    @Override
    protected void alterar() {
        if (isFormValid() && isCPFValid()) {
            String cpf = TextUtils.getValueWithoutMask(txtCPF.getText());

            if (new ClienteDAO().consultarPorEqUk("nuCpf", cpf) != null && 
                    !((Cliente) entity).getNuCpf().equals(cpf)) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("ClienteView.cpfExiste"), 
                        bundle.getString("atencao"),
                        JOptionPane.WARNING_MESSAGE);
                txtCPF.requestFocus();

                return;
            }

            binder.updateModel(entity);

            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(),
                        bundle.getString("ClienteView.confirmarAlterar"),
                        bundle.getString("alterar"), 0) == 0) {
                    new ClienteDAO().salvar((Cliente) entity); // alterar
                    JOptionPane.showMessageDialog((Frame) getParent(),
                            bundle.getString("ClienteView.alteradoSucesso"));
                    reset(true);
                }
            } catch (HibernateException | HeadlessException e) {
                JOptionPane.showMessageDialog((Frame) getParent(),
                        bundle.getString("ClienteView.erroAlterar")
                        + "\n<html><b>" + e.getClass() + "</html></b>\n"
                        + bundle.getString("contateDesenvolvedor"),
                        bundle.getString("ClienteView.erroAlterarTitle"),
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    } // fim do método alterar

    @Override
    protected void excluir() {
        if (!new ClienteDAO().possuiRelacionamento(((Cliente) entity).getCdCliente())) {
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(),
                        bundle.getString("ClienteView.confirmarExcluir"),
                        bundle.getString("excluir"), 0) == 0) {
                    new ClienteDAO().excluir((Cliente) entity); // excluir
                    JOptionPane.showMessageDialog((Frame) getParent(),
                            bundle.getString("ClienteView.excluidoSucesso"));
                    reset(true);
                }
            } catch (HibernateException | HeadlessException e) {
                JOptionPane.showMessageDialog((Frame) getParent(),
                        bundle.getString("ClienteView.erroExcluir")
                        + "\n<html><b>" + e.getClass() + "</html></b>\n"
                        + bundle.getString("contateDesenvolvedor"),
                        bundle.getString("ClienteView.erroExcluirTitle"),
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("ClienteView.clienteEmUso"), 
                        bundle.getString("atencao"), 
                        JOptionPane.WARNING_MESSAGE);
        }
    } // fim do método excluir
    
    private boolean isCPFValid() {
//        boolean validCPF = Validator.isValidCPF(TextUtils.getValueWithoutMask(txtCPF.getText()).trim());
//        
//        if (!validCPF) {
//            txtCPF.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
//            JOptionPane.showMessageDialog(((Frame) getParent()), bundle.getString("cpfInvalido"));
//        }
//        
//        return validCPF;
          return true;
    } // Fim do método isCPFValid

    @Override
    protected boolean validarCampos() {
        boolean valid = true;

        if (TextUtils.getValueWithoutMask(txtCPF.getText()).trim().isEmpty()) {
            txtCPF.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
            valid = false;
        }

        if (txtNome.getText().trim().isEmpty()) {
            txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
            valid = false;
        }

        return valid;
    } // fim do método validarCampos

    @Override
    protected void selecionar() {
        reset(false);
        entity = ((ObjectTableModel<Cliente>) tabelaCliente.getModel()).getValue(tabelaCliente.getSelectedRow());
        binder.updateView(entity);
        
        if (((Cliente) entity).getCdCliente() == 1) {
            btAlterar.setEnabled(false);
            btExcluir.setEnabled(false);
        }
        
        consultar.dispose();
    } // Fim do método selecionar

    @Override
    protected void configEventos() {
        new MyMouseAdapter(btConsultar).setAction(this, KeyEvent.VK_F1, 0, () -> {
            callConsulta();
        });
        new MyMouseAdapter(btNovo).setAction(this, KeyEvent.VK_F2, 0, () -> {
            novo();
        });
        new MyMouseAdapter(btIncluir).setAction(this, KeyEvent.VK_F3, 0, () -> {
            incluir();
        });
        new MyMouseAdapter(btAlterar).setAction(this, KeyEvent.VK_F4, 0, () -> {
            alterar();
        });
        new MyMouseAdapter(btExcluir).setAction(this, KeyEvent.VK_F5, 0, () -> {
            excluir();
        });
        new MyMouseAdapter(btCancelar).setAction(this, KeyEvent.VK_ESCAPE, 0, () -> {
            cancelar();
        });

        // atalho da tela de consulta
        new MyMouseAdapter(btCancelarConsulta).setAction(consultar, KeyEvent.VK_ESCAPE, 0, () -> {
            consultar.dispose();
        });
        new MyMouseAdapter(btSelecionar).setAction(consultar, KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK, () -> {
            selecionar();
        });
    } // fim do método configEventos
    
    private void reset(boolean novo) {
        limpar();
        btIncluir.setEnabled(novo);
        btAlterar.setEnabled(!novo);
        btExcluir.setEnabled(!novo);
        txtCPF.requestFocus();
    } // Fim do método reset

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelarConsulta;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btConsultar1;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSelecionar;
    @Bindable(field = "estado")
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JDialog consultar;
    @Bindable(field = "dtNascimento")
    private com.toedter.calendar.JDateChooser dtNascimento;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblDtNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTable tabelaCliente;
    @Bindable(field = "bairro")
    private javax.swing.JCTextField txtBairro;
    @Bindable(field = "cep")
    private javax.swing.JCFormattedTextField txtCEP;
    @Bindable(field = "nuCpf")
    private javax.swing.JCFormattedTextField txtCPF;
    @Bindable(field = "cidade")
    private javax.swing.JCTextField txtCidade;
    @Bindable(field = "complemento")
    private javax.swing.JCTextField txtComplemento;
    private javax.swing.JCTextField txtConsulta;
    @Bindable(field = "email")
    private javax.swing.JCTextField txtEmail;
    @Bindable(field = "endereco")
    private javax.swing.JCTextField txtEndereco;
    @Bindable(field = "nome")
    private javax.swing.JCTextField txtNome;
    @Bindable(field = "num")
    private javax.swing.JCTextField txtNumero;
    @Bindable(field = "nuTelefone")
    private javax.swing.JCFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

} // fim da classe ClienteView
