/*
 * Copyright 2018 Aluno.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package view;

import model.Produto;
import model.TipoProduto;
import dao.ProdutoDAO;
import dao.TipoProdutoDAO;

import bean.IntFormatter;
import swing.event.MyMouseAdapter;
import util.SwingUtils;
import swing.PromptComboBoxRenderer;
import values.SoftConfig;

import com.towel.bind.annotation.Bindable;
import com.towel.bind.annotation.Form;
import com.towel.swing.combo.ObjectComboBoxModel;
import com.towel.swing.table.ObjectTableModel;

import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.text.BadLocationException;

import org.hibernate.HibernateException;

/**
 *
 * @author Aluno
 */
@Form(Produto.class)
public class ProdutoView extends BaseView {

    /**
     * Creates new form ProdutoView
     * @param parent
     * @param modal
     */
    public ProdutoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    } // fim do método construtor ProdutoView

    @Override
    protected void init() {
        initComponents();
        txtVlVenda.setFocusLostBehavior(JFormattedTextField.COMMIT);
        txtVlCompra.setFocusLostBehavior(JFormattedTextField.COMMIT);
        carregarTipos(cbTipoProduto);
    } // fim do método init

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultar = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbFiltro = new javax.swing.JComboBox<>();
        btConsultar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtConsulta = new javax.swing.JCTextField();
        cbTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        btSelecionar = new javax.swing.JButton();
        btCancelarConsulta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JCTextField();
        SwingUtils.setFieldLength(txtNome, values.Length.Produto.NOME, SwingUtils.FIXED_LENGTH);
        lblTipo = new javax.swing.JLabel();
        cbTipoProduto = new javax.swing.JComboBox<>();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JCTextField();
        SwingUtils.setFieldLength(txtNumero, values.Length.Produto.NU_PRODUTO, SwingUtils.FIXED_LENGTH);
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JCTextField();
        SwingUtils.setFieldLength(txtQuantidade, -1, SwingUtils.NUMERO_VALIDATOR);
        lblVlVenda = new javax.swing.JLabel();
        txtVlVenda = new javax.swing.JCFormattedTextField();
        lblVlCompra = new javax.swing.JLabel();
        txtVlCompra = new javax.swing.JCFormattedTextField();
        btConsultar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btIncluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        consultar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("res/Bundle"); // NOI18N
        consultar.setTitle(bundle.getString("ProdutoView.consultar.title")); // NOI18N
        consultar.setMinimumSize(new java.awt.Dimension(726, 400));
        consultar.setModal(true);
        consultar.setSize(new java.awt.Dimension(0, 0));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")), bundle.getString("ProdutoView.jPanel7.border.title"))); // NOI18N

        jLabel17.setText(bundle.getString("filtro")); // NOI18N

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<String>(bundle.getString("ProdutoView.cbFiltro.array").split(",")));
        cbFiltro.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        cbFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroActionPerformed(evt);
            }
        });

        btConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_search_18pt.png"))); // NOI18N
        btConsultar1.setText(bundle.getString("consultar")); // NOI18N
        btConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultar1ActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        txtConsulta.setPlaceholder(bundle.getString("consulta.placeholder")); // NOI18N
        txtConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultaKeyPressed(evt);
            }
        });
        jPanel2.add(txtConsulta);

        cbTipo.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        jPanel2.add(cbTipo);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(btConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btConsultar1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaProdutoMouseReleased(evt);
            }
        });
        tabelaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        btSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_done_18pt.png"))); // NOI18N
        btSelecionar.setText(bundle.getString("selecionar")); // NOI18N
        btSelecionar.setEnabled(false);

        btCancelarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_cancel_18pt.png"))); // NOI18N
        btCancelarConsulta.setText(bundle.getString("cancelar")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btCancelarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelecionar)
                    .addComponent(btCancelarConsulta))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar.getContentPane());
        consultar.getContentPane().setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(bundle.getString("ProdutoView.title")); // NOI18N
        setMinimumSize(null);
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")), bundle.getString("ProdutoView.jPanel3.border.title"))); // NOI18N

        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText(bundle.getString("ProdutoView.lblNome.text")); // NOI18N

        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });

        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipo.setText(bundle.getString("ProdutoView.lblTipo.text")); // NOI18N

        cbTipoProduto.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        cbTipoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbTipoProdutoFocusGained(evt);
            }
        });

        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumero.setText(bundle.getString("ProdutoView.lblNumero.text")); // NOI18N

        txtNumero.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroFocusGained(evt);
            }
        });

        lblQuantidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQuantidade.setText(bundle.getString("ProdutoView.lblQuantidade.text")); // NOI18N

        txtQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        txtQuantidade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantidadeFocusGained(evt);
            }
        });

        lblVlVenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVlVenda.setText(bundle.getString("ProdutoView.lblVlVenda.text")); // NOI18N

        txtVlVenda.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        txtVlVenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtVlVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVlVendaFocusGained(evt);
            }
        });

        lblVlCompra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVlCompra.setText(bundle.getString("ProdutoView.lblVlCompra.text")); // NOI18N

        txtVlCompra.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        txtVlCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtVlCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVlCompraFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVlVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVlVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblVlCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipoProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVlCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo)
                    .addComponent(cbTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVlVenda)
                    .addComponent(txtVlVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVlCompra)
                    .addComponent(txtVlCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        btConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_search_18pt.png"))); // NOI18N
        btConsultar.setText(bundle.getString("consultar")); // NOI18N

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_fiber_new_18pt.png"))); // NOI18N
        btNovo.setText(bundle.getString("novo")); // NOI18N

        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_add_18pt.png"))); // NOI18N
        btIncluir.setText(bundle.getString("incluir")); // NOI18N

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_update_18pt.png"))); // NOI18N
        btAlterar.setText(bundle.getString("alterar")); // NOI18N
        btAlterar.setEnabled(false);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_delete_forever_18pt.png"))); // NOI18N
        btExcluir.setText(bundle.getString("excluir")); // NOI18N
        btExcluir.setEnabled(false);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_cancel_18pt.png"))); // NOI18N
        btCancelar.setText(bundle.getString("cancelar")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCancelar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btNovo)
                        .addComponent(btConsultar)
                        .addComponent(btIncluir)
                        .addComponent(btAlterar)
                        .addComponent(btExcluir)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
    }//GEN-LAST:event_txtNomeFocusGained

    private void tabelaProdutoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMouseReleased
        if (tabelaProduto.getSelectedRow() != -1) {
            btSelecionar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaProdutoMouseReleased

    private void txtNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusGained
        txtNumero.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
    }//GEN-LAST:event_txtNumeroFocusGained

    private void cbTipoProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbTipoProdutoFocusGained
        cbTipoProduto.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
    }//GEN-LAST:event_cbTipoProdutoFocusGained

    private void txtVlVendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVlVendaFocusGained
        txtVlVenda.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
    }//GEN-LAST:event_txtVlVendaFocusGained

    private void txtVlCompraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVlCompraFocusGained
        txtVlCompra.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
    }//GEN-LAST:event_txtVlCompraFocusGained

    private void txtConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            consultar();
        }
    }//GEN-LAST:event_txtConsultaKeyPressed

    private void tabelaProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaProdutoKeyReleased
        if (tabelaProduto.getSelectedRow() != -1) {
            btSelecionar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaProdutoKeyReleased

    private void btConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultar1ActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultar1ActionPerformed

    private void txtQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeFocusGained
        txtQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
    }//GEN-LAST:event_txtQuantidadeFocusGained

    private void cbFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroActionPerformed
        txtConsulta.setVisible(cbFiltro.getSelectedIndex() != 1);
        cbTipo.setVisible(cbFiltro.getSelectedIndex() == 1);
        cbTipo.setSelectedIndex(-1);
        
        try {
            txtConsulta.getDocument().remove(0, txtConsulta.getDocument().getLength());
        } catch (BadLocationException ex) {
            System.err.println("Error: cbFiltroActionPerformed: " + ex);
        }
    }//GEN-LAST:event_cbFiltroActionPerformed
    
    @Override
    protected void callConsulta() throws HeadlessException {
        consultar.setSize(SoftConfig.WINDOW_WIDTH, consultar.getHeight());
        consultar.setLocationRelativeTo(null);
        cbFiltro.setSelectedIndex(0);
        cbTipo.setSelectedIndex(-1);
        cbTipo.setVisible(false);
        txtConsulta.setText(null);
        carregarTipos(cbTipo);
        
        try {
            carregarTabela(Produto.class, new ProdutoDAO().listar(), 
                    bundle.getString("ProdutoView.tabela.vazia"), 
                    jScrollPane1, tabelaProduto, bundle.getString("ProdutoView.tabela.header"));
            btSelecionar.setEnabled(false);
            consultar.setVisible(true);
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(getParent(), 
                    bundle.getString("ProdutoView.erroCarregar"), 
                    bundle.getString("ProdutoView.erroCarregarTitle"), 
                    JOptionPane.ERROR_MESSAGE);
        }
    } // Fim do método callConsulta
    
    @Override
    protected void consultar() {
        String busca = txtConsulta.getText().trim();

        if ((cbTipo.getSelectedItem() != null && !cbTipo.getSelectedItem().toString().isEmpty()) || 
                (busca != null && !busca.isEmpty())) {
            try {
                Map<Integer, Runnable> map = new HashMap<>();
                map.put(0, () -> {
                    carregarTabela(Produto.class, 
                            new ProdutoDAO().consultarPorLike("nome", busca), 
                            bundle.getString("ProdutoView.tabela.vazia"), 
                            jScrollPane1, tabelaProduto, 
                            bundle.getString("ProdutoView.tabela.header"));
                });
                map.put(1, () -> {
                    carregarTabela(Produto.class, 
                            new ProdutoDAO().consultarPorTipo(cbTipo.getSelectedItem().toString()), 
                            bundle.getString("ProdutoView.tabela.vazia"), 
                            jScrollPane1, tabelaProduto, 
                            bundle.getString("ProdutoView.tabela.header"));
                });
                map.put(2, () -> {
                    carregarTabela(Produto.class, 
                            new ProdutoDAO().consultarPorLike("nuProduto", busca), 
                            bundle.getString("ProdutoView.tabela.vazia"), 
                            jScrollPane1, tabelaProduto, 
                            bundle.getString("ProdutoView.tabela.header"));
                });
                map.get(cbFiltro.getSelectedIndex()).run();
            } catch (HibernateException e) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("erroBusca"));
            }
        } else {
            carregarTabela(Produto.class, 
                    new ProdutoDAO().listar(), 
                    bundle.getString("ProdutoView.tabela.vazia"), 
                    jScrollPane1, tabelaProduto, 
                    bundle.getString("ProdutoView.tabela.header"));
        }
        
        btSelecionar.setEnabled(false);
    } // fim do método consultar
    
    @Override
    protected void novo() throws HeadlessException {
        if (!txtNome.getText().trim().isEmpty() || 
                cbTipoProduto.getSelectedIndex() != -1 || 
                !txtNumero.getText().trim().isEmpty() || 
                !txtQuantidade.getText().trim().isEmpty() || 
                !txtVlVenda.getText().trim().isEmpty() || 
                !txtVlCompra.getText().trim().isEmpty()) {
            if (JOptionPane.showConfirmDialog((Frame) getParent(), 
                    bundle.getString("ProdutoView.confirmarNovo"), 
                    bundle.getString("novo"), 0) == 0) {
                reset(true);
            }
        } else {
            limpar();
            txtNome.requestFocus();
        }
    } // Fim do método novo
    
    @Override
    protected void incluir() {
        if (isFormValid()) {
            entity = new Produto();
            binder.updateModel(entity);
            Produto pNumero = new ProdutoDAO().consultarPorEqUk("nuProduto", txtNumero.getText().trim());
            
            if (pNumero != null) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("ProdutoView.numeroExiste"),
                        bundle.getString("atencao"), 
                        JOptionPane.WARNING_MESSAGE);
                txtNumero.requestFocus();
                
                return;
            }
            
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), 
                        bundle.getString("ProdutoView.confirmarIncluir"), 
                        bundle.getString("incluir"), 0) == 0) {
                    new ProdutoDAO().salvar((Produto) entity); // incluir
                    JOptionPane.showMessageDialog((Frame) getParent(), 
                            bundle.getString("ProdutoView.incluidoSucesso"));
                    reset(true);
                }
            } catch (HibernateException | HeadlessException e) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("ProdutoView.erroIncluir")
                        + "\n<html><b>" + e.getClass() + "</html></b>\n"
                        + bundle.getString("contateDesenvolvedor"), 
                        bundle.getString("ProdutoView.erroIncluirTitle"), 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    } // fim do método incluir
    
    @Override
    protected void alterar() {
        if (isFormValid()) {
            Produto pNumero = new ProdutoDAO().consultarPorEqUk("nuProduto", txtNumero.getText().trim());
            
            if (pNumero != null && !((Produto) entity).getNuProduto().equals(txtNumero.getText().trim())) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("ProdutoView.numeroExiste"),
                        bundle.getString("atencao"), 
                        JOptionPane.WARNING_MESSAGE);
                txtNumero.requestFocus();
                
                return;
            }
            
            binder.updateModel(entity);
            
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), 
                        bundle.getString("ProdutoView.confirmarAlterar"), 
                        bundle.getString("alterar"), 0) == 0) {
                    new ProdutoDAO().salvar((Produto) entity); // alterar
                    JOptionPane.showMessageDialog((Frame) getParent(), 
                            bundle.getString("ProdutoView.alteradoSucesso"));
                    reset(true);
                }
            } catch (HibernateException | HeadlessException e) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("ProdutoView.erroAlterar")
                        + "\n<html><b>" + e.getClass() + "</html></b>\n"
                        + bundle.getString("contateDesenvolvedor"), 
                        bundle.getString("ProdutoView.erroAlterarTitle"), 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    } // fim do método alterar
    
    @Override
    protected void excluir() {
        if (!new ProdutoDAO().possuiRelacionamento(((Produto) entity).getCdProduto())) {
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), 
                        bundle.getString("ProdutoView.confirmarExcluir"), 
                        bundle.getString("excluir"), 0) == 0) {
                    new ProdutoDAO().excluir((Produto) entity); // excluir
                    JOptionPane.showMessageDialog((Frame) getParent(), 
                            bundle.getString("ProdutoView.excluidoSucesso"));
                    reset(true);
                }
            } catch (HibernateException | HeadlessException e) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("ProdutoView.erroExcluir")
                        + "\n<html><b>" + e.getClass() + "</html></b>\n"
                        + bundle.getString("contateDesenvolvedor"), 
                        bundle.getString("ProdutoView.erroExcluirTitle"), 
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("ProdutoView.produtoEmUso"), 
                        bundle.getString("atencao"), 
                        JOptionPane.WARNING_MESSAGE);
        }
    } // fim do método excluir
    
    @Override
    protected boolean validarCampos() throws HeadlessException {
        boolean valid = true;
        Border border = javax.swing.BorderFactory.createLineBorder(java.awt.Color.red);
        
        if (txtNome.getText().trim().isEmpty()) {
            txtNome.setBorder(border);
            valid = false;
        }
        
        if (cbTipoProduto.getSelectedIndex() == -1) {
            cbTipoProduto.setBorder(border);
            valid = false;
        }
        
        if (txtNumero.getText().trim().isEmpty()) {
            txtNumero.setBorder(border);
            valid = false;
        }
        
        if (txtQuantidade.getText().trim().isEmpty()) {
            txtQuantidade.setBorder(border);
            valid = false;
        }
        
        if (txtVlVenda.getText().trim().isEmpty()) {
            txtVlVenda.setBorder(border);
            valid = false;
        }
        
        if (txtVlCompra.getText().trim().isEmpty()) {
            txtVlCompra.setBorder(border);
            valid = false;
        }
        
        return valid;
    } // fim do método validarCampos
    
    @Override
    protected void selecionar() {
            reset(false);
            entity = ((ObjectTableModel<Produto>) tabelaProduto.getModel()).getValue(tabelaProduto.getSelectedRow());
            binder.updateView(entity);
            consultar.dispose();
    } // Fim do método selecionar
    
    @Override
    protected void configEventos() {
        new MyMouseAdapter(btConsultar).setAction(this, KeyEvent.VK_F1, 0, () -> {
            callConsulta();
        });
        new MyMouseAdapter(btNovo).setAction(this, KeyEvent.VK_F2, 0, () -> {
            novo();
        });
        new MyMouseAdapter(btIncluir).setAction(this, KeyEvent.VK_F3, 0, () -> {
            incluir();
        });
        new MyMouseAdapter(btAlterar).setAction(this, KeyEvent.VK_F4, 0, () -> {
            alterar();
        });
        new MyMouseAdapter(btExcluir).setAction(this, KeyEvent.VK_F5, 0, () -> {
            excluir();
        });
        new MyMouseAdapter(btCancelar).setAction(this, KeyEvent.VK_ESCAPE, 0, () -> {
            cancelar();
        });
        
        // atalho da tela de consulta
        new MyMouseAdapter(btCancelarConsulta).setAction(consultar, KeyEvent.VK_ESCAPE, 0, () -> {
            consultar.dispose();
        });
        new MyMouseAdapter(btSelecionar).setAction(consultar, KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK, () -> {
            selecionar();
        });
    } // fim do método configEventos
    
    private void carregarTipos(JComboBox comboBox) {
        try {
            List<TipoProduto> tiposProduto = new TipoProdutoDAO().listar();
            ObjectComboBoxModel<TipoProduto> comboBoxModel = new ObjectComboBoxModel<>();
            comboBoxModel.setData(tiposProduto);
            comboBox.setModel(comboBoxModel);
            comboBox.setRenderer(new PromptComboBoxRenderer(bundle.getString("selecione")));
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(getParent(), 
                    bundle.getString("ProdutoView.erroCarregarTipos"), 
                    bundle.getString("ProdutoView.erroCarregarTiposTitle"), 
                    JOptionPane.ERROR_MESSAGE);
        }
    } // Fim do método carregarTipos
    
    private void reset(boolean novo) {
        limpar();
        btIncluir.setEnabled(novo);
        btAlterar.setEnabled(!novo);
        btExcluir.setEnabled(!novo);
        txtNome.requestFocus();
    } // Fim do método reset

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelarConsulta;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btConsultar1;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JComboBox<String> cbTipo;
    @Bindable(field = "tipoProduto")
    private javax.swing.JComboBox<String> cbTipoProduto;
    private javax.swing.JDialog consultar;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblVlCompra;
    private javax.swing.JLabel lblVlVenda;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JCTextField txtConsulta;
    @Bindable(field = "nome")
    private javax.swing.JCTextField txtNome;
    @Bindable(field = "nuProduto")
    private javax.swing.JCTextField txtNumero;
    @Bindable(field = "qtdProduto", formatter = IntFormatter.class)
    private javax.swing.JCTextField txtQuantidade;
    @Bindable(field = "vlCompra")
    private javax.swing.JCFormattedTextField txtVlCompra;
    @Bindable(field = "vlVenda")
    private javax.swing.JCFormattedTextField txtVlVenda;
    // End of variables declaration//GEN-END:variables

} // fim da classe ProdutoView
