/*
 * Copyright 2018 Aluno.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package view;

import dao.TipoMovimentacaoDAO;
import model.TipoMovimentacao;
import swing.event.MyMouseAdapter;
import util.SwingUtils;
import values.SoftConfig;

import com.towel.bind.annotation.Bindable;
import com.towel.bind.annotation.Form;
import com.towel.swing.table.ObjectTableModel;

import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

import org.hibernate.HibernateException;

/**
 *
 * @author Aluno
 */
@Form(TipoMovimentacao.class)
public class TipoMovimentacaoView extends BaseView {

    /**
     * Creates new form TipoMovimentacaoView
     * @param parent
     * @param modal
     */
    public TipoMovimentacaoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    } // fim do método construtor TipoMovimentacaoView

    @Override
    protected void init() {
        initComponents();
    } // fim do método init

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultar = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbFiltro = new javax.swing.JComboBox<>();
        btConsultar1 = new javax.swing.JButton();
        txtConsulta = new javax.swing.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTipoMovimentacao = new javax.swing.JTable();
        btSelecionar = new javax.swing.JButton();
        btCancelarConsulta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btIncluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JCTextField();
        SwingUtils.setFieldLength(txtTipo, values.Length.TipoMovimentacao.TIPO, SwingUtils.FIXED_LENGTH);
        btConsultar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        consultar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("res/Bundle"); // NOI18N
        consultar.setTitle(bundle.getString("TipoMovimentacaoView.consultar.title")); // NOI18N
        consultar.setMinimumSize(new java.awt.Dimension(726, 400));
        consultar.setModal(true);
        consultar.setSize(new java.awt.Dimension(0, 0));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")), bundle.getString("TipoMovimentacaoView.jPanel7.border.title"))); // NOI18N

        jLabel17.setText(bundle.getString("filtro")); // NOI18N

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<String>(bundle.getString("TipoMovimentacaoView.cbFiltro.array").split(",")));
        cbFiltro.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        btConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_search_18pt.png"))); // NOI18N
        btConsultar1.setText(bundle.getString("consultar")); // NOI18N
        btConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultar1ActionPerformed(evt);
            }
        });

        txtConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        txtConsulta.setPlaceholder(bundle.getString("consulta.placeholder")); // NOI18N
        txtConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(btConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar1))
                .addGap(10, 10, 10))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));

        tabelaTipoMovimentacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaTipoMovimentacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaTipoMovimentacaoMouseReleased(evt);
            }
        });
        tabelaTipoMovimentacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaTipoMovimentacaoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaTipoMovimentacao);

        btSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_done_18pt.png"))); // NOI18N
        btSelecionar.setText(bundle.getString("selecionar")); // NOI18N
        btSelecionar.setEnabled(false);

        btCancelarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_cancel_18pt.png"))); // NOI18N
        btCancelarConsulta.setText(bundle.getString("cancelar")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btCancelarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelecionar)
                    .addComponent(btCancelarConsulta))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar.getContentPane());
        consultar.getContentPane().setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(bundle.getString("TipoMovimentacaoView.title")); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(726, 726));

        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_add_18pt.png"))); // NOI18N
        btIncluir.setText(bundle.getString("incluir")); // NOI18N

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_update_18pt.png"))); // NOI18N
        btAlterar.setText(bundle.getString("alterar")); // NOI18N
        btAlterar.setEnabled(false);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_cancel_18pt.png"))); // NOI18N
        btCancelar.setText(bundle.getString("cancelar")); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")), bundle.getString("TipoMovimentacaoView.jPanel3.border.title"))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(bundle.getString("TipoMovimentacaoView.jLabel1.text")); // NOI18N

        txtTipo.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
        txtTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        btConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_search_18pt.png"))); // NOI18N
        btConsultar.setText(bundle.getString("consultar")); // NOI18N

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_fiber_new_18pt.png"))); // NOI18N
        btNovo.setText(bundle.getString("novo")); // NOI18N

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/ic_delete_forever_18pt.png"))); // NOI18N
        btExcluir.setText(bundle.getString("excluir")); // NOI18N
        btExcluir.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCancelar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btNovo)
                        .addComponent(btConsultar)
                        .addComponent(btIncluir)
                        .addComponent(btAlterar)
                        .addComponent(btExcluir)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoFocusGained
        txtTipo.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.shadow")));
    }//GEN-LAST:event_txtTipoFocusGained

    private void tabelaTipoMovimentacaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTipoMovimentacaoMouseReleased
        if (tabelaTipoMovimentacao.getSelectedRow() != -1) {
            btSelecionar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaTipoMovimentacaoMouseReleased

    private void txtConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            consultar();
        }
    }//GEN-LAST:event_txtConsultaKeyPressed

    private void tabelaTipoMovimentacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaTipoMovimentacaoKeyReleased
        if (tabelaTipoMovimentacao.getSelectedRow() != -1) {
            btSelecionar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaTipoMovimentacaoKeyReleased

    private void btConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultar1ActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultar1ActionPerformed
    
    @Override
    protected void callConsulta() throws HeadlessException {
        consultar.setSize(SoftConfig.WINDOW_WIDTH, consultar.getHeight());
        consultar.setLocationRelativeTo(null);
        cbFiltro.setSelectedIndex(0);
        txtConsulta.setText(null);
        
        try {
            carregarTabela(TipoMovimentacao.class, new TipoMovimentacaoDAO().listar(), 
                    bundle.getString("TipoMovimentacaoView.tabela.vazia"), 
                    jScrollPane1, tabelaTipoMovimentacao, 
                    bundle.getString("TipoMovimentacaoView.tabela.header"));
            btSelecionar.setEnabled(false);
            consultar.setVisible(true);
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(getParent(), 
                    bundle.getString("TipoMovimentacaoView.erroCarregar"), 
                    bundle.getString("TipoMovimentacaoView.erroCarregarTitle"), 
                    JOptionPane.ERROR_MESSAGE);
        }
    } // Fim do método callConsulta
    
    @Override
    protected void consultar() {
        try {
            carregarTabela(TipoMovimentacao.class, 
                    new TipoMovimentacaoDAO().consultarPorTipo(txtConsulta.getText()), 
                    bundle.getString("TipoMovimentacaoView.tabela.vazia"), jScrollPane1, 
                    tabelaTipoMovimentacao, bundle.getString("TipoMovimentacaoView.tabela.header"));
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog((Frame) getParent(), 
                    bundle.getString("erroBusca"));
        }
        
        btSelecionar.setEnabled(false);
    } // fim do método consultar
    
    @Override
    protected void novo() throws HeadlessException {
        if (!txtTipo.getText().trim().isEmpty()) {
            if (JOptionPane.showConfirmDialog((Frame) getParent(), 
                    bundle.getString("TipoMovimentacaoView.confirmarNovo"), 
                    bundle.getString("novo"), 0) == 0) {
                reset(true);
            }
        } else {
            limpar();
            txtTipo.requestFocus();
        }
    } // Fim do método novo
    
    @Override
    protected void incluir() {
        if (isFormValid()) {
            entity = new TipoMovimentacao();
            TipoMovimentacao tmTipo = new TipoMovimentacaoDAO().consultarPorTipoUk(txtTipo.getText().trim());
            
            if (tmTipo != null) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("TipoMovimentacaoView.tipoExiste"),
                        bundle.getString("atencao"), 
                        JOptionPane.WARNING_MESSAGE);
                txtTipo.requestFocus();
                
                return;
            }
            
            binder.updateModel(entity);
            
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), 
                        bundle.getString("TipoMovimentacaoView.confirmarIncluir"), 
                        bundle.getString("incluir"), 0) == 0) {
                    new TipoMovimentacaoDAO().salvar((TipoMovimentacao) entity); // incluir
                    JOptionPane.showMessageDialog((Frame) getParent(), 
                            bundle.getString("TipoMovimentacaoView.incluidoSucesso"));
                    reset(true);
                }
            } catch (HibernateException | HeadlessException e) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("TipoMovimentacaoView.erroIncluir")
                        + "\n<html><b>" + e.getClass() + "</html></b>\n"
                        + bundle.getString("contateDesenvolvedor"), 
                        bundle.getString("TipoMovimentacaoView.erroIncluirTitle"), 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    } // fim do método incluir
    
    @Override
    protected void alterar() {
        if (isFormValid()) {
            TipoMovimentacao tmTipo = new TipoMovimentacaoDAO().consultarPorTipoUk(txtTipo.getText().trim());
            
            if (tmTipo != null && !((TipoMovimentacao) entity).getTipo().equals(txtTipo.getText().trim())) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("TipoMovimentacaoView.tipoExiste"),
                        bundle.getString("atencao"), 
                        JOptionPane.WARNING_MESSAGE);
                txtTipo.requestFocus();
                
                return;
            }
            
            binder.updateModel(entity);
            
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), 
                        bundle.getString("TipoMovimentacaoView.confirmarAlterar"), 
                        bundle.getString("alterar"), 0) == 0) {
                    new TipoMovimentacaoDAO().salvar((TipoMovimentacao) entity); // alterar
                    JOptionPane.showMessageDialog((Frame) getParent(), 
                            bundle.getString("TipoMovimentacaoView.alteradoSucesso"));
                    reset(true);
                }
            } catch (HibernateException | HeadlessException e) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("TipoMovimentacaoView.erroAlterar")
                        + "\n<html><b>" + e.getClass() + "</html></b>\n"
                        + bundle.getString("contateDesenvolvedor"), 
                        bundle.getString("TipoMovimentacaoView.erroAlterarTitle"), 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    } // fim do método alterar
    
    @Override
    protected void excluir() {
        if (!new TipoMovimentacaoDAO().possuiRelacionamento(((TipoMovimentacao) entity).getCdTipoMovimentacao())) {
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), 
                        bundle.getString("TipoMovimentacaoView.confirmarExcluir"), 
                        bundle.getString("excluir"), 0) == 0) {
                    new TipoMovimentacaoDAO().excluir((TipoMovimentacao) entity); // excluir
                    JOptionPane.showMessageDialog((Frame) getParent(), 
                            bundle.getString("TipoMovimentacaoView.excluidoSucesso"));
                    reset(true);
                }
            } catch (HibernateException | HeadlessException e) {
                JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("TipoMovimentacaoView.erroExcluir")
                        + "\n<html><b>" + e.getClass() + "</html></b>\n"
                        + bundle.getString("contateDesenvolvedor"), 
                        bundle.getString("TipoMovimentacaoView.erroExcluirTitle"), 
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog((Frame) getParent(), 
                        bundle.getString("TipoMovimentacaoView.tipoMovimentacaoEmUso"), 
                        bundle.getString("atencao"), 
                        JOptionPane.WARNING_MESSAGE);
        }
    } // fim do método excluir
    
    @Override
    protected boolean validarCampos() {
        boolean valid = true;
        
        if (txtTipo.getText().trim().isEmpty()) {
            txtTipo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
            valid = false;
        }
        
        return valid;
    } // fim do método validarCampos
    
    @Override
    protected void selecionar() {
        reset(false);
        entity = ((ObjectTableModel<TipoMovimentacao>) tabelaTipoMovimentacao.getModel()).getValue(tabelaTipoMovimentacao.getSelectedRow());
        binder.updateView(entity);
        consultar.dispose();
    } // Fim do método selecionar
    
    @Override
    protected void configEventos() {
        new MyMouseAdapter(btConsultar).setAction(this, KeyEvent.VK_F1, 0, () -> {
            callConsulta();
        });
        new MyMouseAdapter(btNovo).setAction(this, KeyEvent.VK_F2, 0, () -> {
            novo();
        });
        new MyMouseAdapter(btIncluir).setAction(this, KeyEvent.VK_F3, 0, () -> {
            incluir();
        });
        new MyMouseAdapter(btAlterar).setAction(this, KeyEvent.VK_F4, 0, () -> {
            alterar();
        });
        new MyMouseAdapter(btExcluir).setAction(this, KeyEvent.VK_F5, 0, () -> {
            excluir();
        });
        new MyMouseAdapter(btCancelar).setAction(this, KeyEvent.VK_ESCAPE, 0, () -> {
            cancelar();
        });
        
        // atalho da tela de consulta
        new MyMouseAdapter(btCancelarConsulta).setAction(consultar, KeyEvent.VK_ESCAPE, 0, () -> {
            consultar.dispose();
        });
        new MyMouseAdapter(btSelecionar).setAction(consultar, KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK, () -> {
            selecionar();
        });
    } // fim do método configEventos
    
    private void reset(boolean novo) {
        limpar();
        btIncluir.setEnabled(novo);
        btAlterar.setEnabled(!novo);
        btExcluir.setEnabled(!novo);
        txtTipo.requestFocus();
    } // Fim do método reset

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelarConsulta;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btConsultar1;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JDialog consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTipoMovimentacao;
    private javax.swing.JCTextField txtConsulta;
    @Bindable(field = "tipo")
    private javax.swing.JCTextField txtTipo;
    // End of variables declaration//GEN-END:variables

} // fim da classe CadTipoMovimentacao
